package main.ui.help;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JDialog;
import javax.swing.Timer;
import main.App;
import main.resource.Language;
import main.resource.Resources;
import main.util.Fn;

/**
 *
 * @author Bunnyspa
 */
public class HelpAboutDialog extends JDialog {

    private final App app;
    private boolean fired = false;

    private final Timer timer = new Timer(1000, (e) -> {
        if (!fired) {
            fire();
            fired = true;
        }
    });

    public HelpAboutDialog(App app) {
        this.app = app;
        initComponents();
        init();
    }

    private void init() {
        setTitle(app.getText(Language.HELP_ABOUT));
        imageLabel.setIcon(Resources.BANNER);
        label.setText(Fn.toHTML("<center>" + App.NAME_EN + "</center>" + System.lineSeparator()
                + "Developer: Bunnyspa" + System.lineSeparator()
                + "Email:" + System.lineSeparator()
                + "bunnyspa@naver.com" + System.lineSeparator()
                + "bunnyspa242@gmail.com" + System.lineSeparator()
                + "(Korean and English)" + System.lineSeparator()
                + System.lineSeparator()
                + "This application is a free fan-made application." + System.lineSeparator()
                + "Girls' Frontline and its related images are registered trademarks of Shanghai Sunborn Network Technology Co., Ltd." + System.lineSeparator()
                + "This application is not affiliated with Shanghai Sunborn Network Technology Co., Ltd. in any way." + System.lineSeparator()
                + System.lineSeparator()
                + "Stat presets are based on the following thread: https://gall.dcinside.com/m/micateam/999288" + System.lineSeparator()
                + System.lineSeparator()
                + "[English Translation]" + System.lineSeparator()
                + "Bunnyspa" + System.lineSeparator()
                + System.lineSeparator()
                + "[Japanese Translation Team]" + System.lineSeparator()
                + "xpfjqja" + System.lineSeparator()
                + "apple" + System.lineSeparator()
                + "naganeko" + System.lineSeparator()
                + "ひかげ" + System.lineSeparator()
        ));

        closeButton.setText(app.getText(Language.ACTION_CLOSE));

        addListeners();
        pack();
    }

    private void addListeners() {
        Fn.addEscDisposeListener(this);
        Fn.getAllComponents(this).forEach((c) -> {
            c.addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent e) {
                    fired = false;
                    timer.start();
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                    timer.stop();
                }
            });
        });
    }

    private void fire() {
        Fn.open(this, HelpAboutHiddenDialog.getInstance(app));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        closeButton.setText("닫기");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("text");
        label.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeButton))
                    .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
