package main.ui.help;

import javax.swing.JDialog;
import main.App;
import main.resource.Language;
import main.util.Fn;
import main.util.IO;

/**
 *
 * @author Bunnyspa
 */
public class HelpDialog extends JDialog {

    private static final String LINK_CHANGELOG = "https://drive.google.com/open?id=1ekGRvd3anlfUWBJ_pBTfYR6N79g4rWc0";

    private final App app;

    public static HelpDialog getInstance(App app) {
        return new HelpDialog(app);
    }

    private HelpDialog(App app) {
        this.app = app;
        initComponents();
        init();
    }

    private void init() {
        setTitle(app.getText(Language.HELP_TITLE));

        chipButton.setText(app.getText(Language.HELP_CHIP));
        appButton.setText(app.getText(Language.HELP_PROGRAM));
        proxyButton.setText(app.getText(Language.HELP_PROXY));
        changelogButton.setText(app.getText(Language.HELP_CHANGELOG));
        aboutButton.setText(app.getText(Language.HELP_ABOUT));
        closeButton.setText(app.getText(Language.ACTION_CLOSE));

        changelogButton.setVisible(false); // TODO: visible?

        addListeners();
        pack();
    }

    private void addListeners() {
        Fn.addEscDisposeListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chipButton = new javax.swing.JButton();
        appButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        proxyButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();
        changelogButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("도움말");
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        chipButton.setText("칩셋 가이드");
        chipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chipButtonActionPerformed(evt);
            }
        });

        appButton.setText("칩셋 조합기 가이드");
        appButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appButtonActionPerformed(evt);
            }
        });

        closeButton.setText("닫기");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        proxyButton.setText("프록시 가이드");
        proxyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proxyButtonActionPerformed(evt);
            }
        });

        aboutButton.setText("정보");
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButtonActionPerformed(evt);
            }
        });

        changelogButton.setText("업데이트 정보");
        changelogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changelogButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chipButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(appButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(proxyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aboutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changelogButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chipButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proxyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changelogButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aboutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void chipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chipButtonActionPerformed
        Fn.open(this, new HelpChipDialog(app));
    }//GEN-LAST:event_chipButtonActionPerformed

    private void appButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appButtonActionPerformed
        Fn.open(this, new HelpAppDialog(app));
    }//GEN-LAST:event_appButtonActionPerformed

    private void proxyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proxyButtonActionPerformed
        Fn.open(this, new HelpProxyDialog(app));
    }//GEN-LAST:event_proxyButtonActionPerformed

    private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButtonActionPerformed
        Fn.open(this, new HelpAboutDialog(app));
    }//GEN-LAST:event_aboutButtonActionPerformed

    private void changelogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changelogButtonActionPerformed
        IO.openWeb(app, this, LINK_CHANGELOG);
    }//GEN-LAST:event_changelogButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutButton;
    private javax.swing.JButton appButton;
    private javax.swing.JButton changelogButton;
    private javax.swing.JButton chipButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton proxyButton;
    // End of variables declaration//GEN-END:variables
}
