package main.ui.help;

import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.Timer;
import javax.swing.border.EmptyBorder;
import main.App;
import main.ui.resource.AppImage;
import main.ui.resource.AppText;
import main.util.Fn;

/**
 *
 * @author Bunnyspa
 */
public class HelpAppDialog extends JDialog {

    private final App app;
    private final List<ImageCycler> cyclers = new ArrayList<>();

    private class ImageCycler {

        private final JLabel label;
        private final ImageIcon[] icons;
        private final Timer timer;
        private int cycle;

        public ImageCycler(JLabel label, ImageIcon... icons) {
            this.label = label;
            if (0 < icons.length) {
                label.setIcon(icons[0]);
            }
            this.icons = icons;
            cycle = 0;
            timer = new Timer(1000, (e) -> cycleImage());
            timer.start();
        }

        private void cycleImage() {
            cycle = (cycle + 1) % icons.length;
            label.setIcon(icons[cycle]);
        }

        public void dispose() {
            timer.stop();
        }
    }

    private class IconText {

        final ImageIcon[] icons;
        final String text;

        public IconText(String text, ImageIcon... icons) {
            this.icons = icons;
            this.text = text;
        }
    }

    public HelpAppDialog(App app) {
        this.app = app;
        initComponents();
        init();
    }

    private void init() {
        setTitle(app.getText(AppText.HELP_PROGRAM));
        closeButton.setText(app.getText(AppText.ACTION_CLOSE));
        addTabs();
        addListeners();
        pack();
    }

    private void addListeners() {
        Fn.addEscDisposeListener(this);
    }

    private void addTabs() {
        aTabbedPane.addTab(app.getText(AppText.HELP_APP_IMPORT), generatePanels(new IconText(app.getText(AppText.HELP_APP_IMPORT_PROXY), AppImage.PHONE),
                new IconText(app.getText(AppText.HELP_APP_IMPORT_IMAGESCAN), AppImage.PICTURE),
                new IconText(app.getText(AppText.HELP_APP_IMPORT_OPEN), AppImage.OPEN)
        ));
        aTabbedPane.addTab(app.getText(AppText.HELP_APP_OPTIMIZE), generatePanels(new IconText(app.getText(AppText.HELP_APP_OPTIMIZE_FILTER), AppImage.FILTER, AppImage.FILTER_APPLY),
                new IconText(app.getText(AppText.HELP_APP_OPTIMIZE_SETTING), AppImage.SETTING, AppImage.SETTING_PRESET, AppImage.SETTING_STAT, AppImage.SETTING_PT),
                new IconText(app.getText(AppText.HELP_APP_OPTIMIZE_MARK), AppImage.UNCHECKED, AppImage.CHECKED)
        ));
    }

    private JPanel generatePanels(IconText... its) {
        JPanel out = new JPanel();
        out.setLayout(new BoxLayout(out, BoxLayout.Y_AXIS));
        for (int i = 0; i < its.length; i++) {
            IconText it = its[i];
            out.add(generatePanel(it.text, it.icons));
            if (i < its.length - 1) {
                out.add(new JSeparator(JSeparator.HORIZONTAL));
            }
        }
        return out;
    }

    private JPanel generatePanel(String text, ImageIcon... icons) {
        JPanel out = new JPanel(new BorderLayout(10, 10));

        JLabel iconLabel = new JLabel();
        ImageCycler cycler = new ImageCycler(iconLabel, icons);
        cyclers.add(cycler);

        JLabel textLabel = new JLabel(text);

        out.add(iconLabel, BorderLayout.LINE_START);
        out.add(textLabel, BorderLayout.CENTER);
        out.setBorder(new EmptyBorder(5, 5, 5, 5));
        return out;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        aTabbedPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("칩셋 조합기 가이드");
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        closeButton.setText("닫기");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 519, Short.MAX_VALUE)
                        .addComponent(closeButton))
                    .addComponent(aTabbedPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cyclers.forEach((c) -> c.dispose());
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane aTabbedPane;
    private javax.swing.JButton closeButton;
    // End of variables declaration//GEN-END:variables
}
