package main.ui.dialog;

import java.awt.Dimension;
import java.awt.Font;
import java.util.Locale;
import javax.swing.JDialog;
import javax.swing.SwingConstants;
import javax.swing.border.EmptyBorder;
import main.App;
import main.setting.Setting;
import main.ui.component.ColorLabel;
import main.ui.resource.GFLResources;
import main.ui.resource.GFLTexts;
import main.util.Fn;
import main.util.IO;
import main.util.Ref;

/**
 *
 * @author Bunnyspa
 */
public class AppSettingDialog extends JDialog {

    private static final int GAP = 5;

    private final App app;
    private Ref<Integer> size;
    private ColorLabel aLabel;

    public static AppSettingDialog getInstance(App app) {
        return new AppSettingDialog(app);
    }

    private AppSettingDialog(App app) {
        initComponents();
        this.app = app;
        init();
    }

    private void init() {
        setTitle(app.getText(GFLTexts.DISPLAY_TITLE));

        languagePanel.setBorder(new EmptyBorder(GAP, GAP, GAP, GAP));
        colorFontPanel.setBorder(new EmptyBorder(GAP, GAP, GAP, GAP));

        aTabbedPane.addTab(app.getText(GFLTexts.DISPLAY_LANGUAGE_TITLE), languagePanel);
        aTabbedPane.addTab(app.getText(GFLTexts.DISPLAY_COLORFONT_TITLE), colorFontPanel);

        exportPropButton.setText(app.getText(GFLTexts.DISPLAY_EXPORT));
        langInfoLabel.setText(app.getText(GFLTexts.DISPLAY_HOWTO_ADDLANGUAGE));
        fontResetButton.setText(app.getText(GFLTexts.DISPLAY_FONT_RESET));
        okButton.setText(app.getText(GFLTexts.ACTION_OK));
        cancelButton.setText(app.getText(GFLTexts.ACTION_CANCEL));

        aLabel = new ColorLabel(app);
        aLabel.setHorizontalAlignment(SwingConstants.CENTER);
        previewPanel.add(aLabel);

        IO.getLocales().forEach((locale) -> localeComboBox.addItem(getLocaleName(locale)));

        localeComboBox.setSelectedItem(getLocaleName(app.setting.locale));
        setColor(app.setting.colorPreset);
        size = new Ref<>(app.setting.fontSize);
        fontSpinner.setValue(size.v);

        Dimension d = app.mf.getPreferredDialogSize();
        setPreferredSize(new Dimension(d.width, getHeight()));

        previewFont();
        addListeners();
        pack();
    }

    private void addListeners() {
        exportPropButton.addActionListener((e) -> IO.exportProps(app, this));
        colorButton.addActionListener((e) -> toggleColor());
        fontSpinner.addChangeListener((e) -> {
            size.v = (int) fontSpinner.getValue();
            previewFont();
        });

        Fn.addEscDisposeListener(this);
    }

    private int colorPreset;

    private static String getLocaleName(Locale locale) {
        return locale.toLanguageTag() + " : " + locale.getDisplayName(locale);
    }

    private static String getColorStr(int preset) {
        switch (preset) {
            case Setting.COLOR_NORMAL:
                return GFLTexts.DISPLAY_COLOR_NORMAL;
            case Setting.COLOR_COLORBLIND:
                return GFLTexts.DISPLAY_COLOR_COLORBLIND;
            default:
                throw new AssertionError();
        }
    }

    private void setColor(int cp) {
        colorPreset = cp % Setting.NUM_COLOR;
        colorButton.setText(app.getText(getColorStr(colorPreset)));
        aLabel.setColorPreset(colorPreset);
        aLabel.repaint();
    }

    private void toggleColor() {
        setColor(colorPreset + 1);
    }

    private void previewFont() {
        aLabel.setText("");
        aLabel.setFont(getSelectedFont());
        String s = app.getText(GFLTexts.DISPLAY_LANGUAGE_PREVIEW);
        aLabel.setText(s);
    }

    private Locale getSelectedLocale() {
        return IO.getLocales().get(localeComboBox.getSelectedIndex());
    }

    private Font getSelectedFont() {
        return GFLResources.getDefaultFont().deriveFont(Float.valueOf(size.v));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        languagePanel = new javax.swing.JPanel();
        langInfoLabel = new javax.swing.JLabel();
        localeComboBox = new javax.swing.JComboBox<>();
        exportPropButton = new javax.swing.JButton();
        colorFontPanel = new javax.swing.JPanel();
        fontSpinner = new javax.swing.JSpinner();
        colorButton = new javax.swing.JButton();
        previewPanel = new javax.swing.JPanel();
        fontResetButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        aTabbedPane = new javax.swing.JTabbedPane();

        langInfoLabel.setText("lang info");

        exportPropButton.setText("save prop");

        javax.swing.GroupLayout languagePanelLayout = new javax.swing.GroupLayout(languagePanel);
        languagePanel.setLayout(languagePanelLayout);
        languagePanelLayout.setHorizontalGroup(
            languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(langInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, languagePanelLayout.createSequentialGroup()
                .addComponent(localeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exportPropButton))
        );
        languagePanelLayout.setVerticalGroup(
            languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(languagePanelLayout.createSequentialGroup()
                .addGroup(languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportPropButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(langInfoLabel))
        );

        fontSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        fontSpinner.setPreferredSize(new java.awt.Dimension(50, 22));

        colorButton.setText("색상: 일반");

        previewPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        previewPanel.setPreferredSize(new java.awt.Dimension(400, 200));
        previewPanel.setLayout(new java.awt.GridLayout(1, 0));

        fontResetButton.setText("글꼴 크기 리셋");
        fontResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontResetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout colorFontPanelLayout = new javax.swing.GroupLayout(colorFontPanel);
        colorFontPanel.setLayout(colorFontPanelLayout);
        colorFontPanelLayout.setHorizontalGroup(
            colorFontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(previewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(colorFontPanelLayout.createSequentialGroup()
                .addComponent(colorButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fontSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fontResetButton))
        );
        colorFontPanelLayout.setVerticalGroup(
            colorFontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorFontPanelLayout.createSequentialGroup()
                .addGroup(colorFontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fontSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fontResetButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(previewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("색상/글꼴 설정");
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setType(java.awt.Window.Type.UTILITY);

        okButton.setText("확인");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("취소");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        aTabbedPane.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addContainerGap())
            .addComponent(aTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(aTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        app.setting.locale = getSelectedLocale();
        app.setting.colorPreset = colorPreset;
        app.setting.fontSize = (int) fontSpinner.getValue();
        app.mf.refreshDisplay();

        app.mf.packAndSetInitSize();
        app.mf.settingFile_save();
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void fontResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontResetButtonActionPerformed
        fontSpinner.setValue(Setting.DEFAULT_FONTSIZE);
    }//GEN-LAST:event_fontResetButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane aTabbedPane;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton colorButton;
    private javax.swing.JPanel colorFontPanel;
    private javax.swing.JButton exportPropButton;
    private javax.swing.JButton fontResetButton;
    private javax.swing.JSpinner fontSpinner;
    private javax.swing.JLabel langInfoLabel;
    private javax.swing.JPanel languagePanel;
    private javax.swing.JComboBox<String> localeComboBox;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel previewPanel;
    // End of variables declaration//GEN-END:variables
}
